---

- name: APT-REPOSITORY | add repository
  apt_repository: repo='deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports main' state=present
  when: redis_use_apt_backports == true

- name: APT | install redis
  apt: pkg=redis-server state=present update_cache=yes cache_valid_time=3600 default_release={{ redis_apt_target }}

- name: TEMPLATE | Deploy Redis config file
  template: src=etc/redis/redis.conf.j2 dest=/etc/redis/redis.conf
  register: configchg

- service: name=redis-server state=restarted
  when: redis_restart_on_config_update == true and configchg | changed

- service: name=redis-server state=started enabled={{ redis_enable }}
  when: redis_service_manage
