---

- name: APT-REPOSITORY | add repository
  apt_repository: repo='deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports main' state=present
  when: redis_use_apt_backports

- name: APT | install redis
  apt: pkg=redis-server state=present update_cache=yes cache_valid_time=3600 default_release={{ redis_apt_target }}

- name: TEMPLATE | Deploy Redis config file
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify: restart redis

- name: SERVICE | Ensure redis is started with enable state
  service: name=redis-server state=started enabled={{ redis_enable }}
  when: redis_service_manage
